Name = "ahead"
ExternalHost = "localhost"
ExternalPort = 2020
InternalHost = "localhost"
InternalPort = 2021
Cert = "cert.pem"
Key = "key.pem"

[Storer]
Host = "localhost"
Port = 26257
User = "ahead"
Database = "ahead"
Cert = "certs/client.ahead.crt"
Key = "certs/client.ahead.key"
RootCert = "certs/ca.crt"
