ExternalHost = "localhost"
ExternalPort = 2020
InternalHost = "localhost"
InternalPort = 2021
Cert = "cert.pem"
Key = "key.pem"

[Storer]
User = "ahead"
Password = "123"
Host = "db"
Port = 5432
Database = "ahead"
